# -*- coding: utf-8 -*-
"""numpy_assignment_01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Mk1vz1UuwC4RKd1uAOhOJ2mq5W07VxIr
"""

import numpy as np
a = np.array([[10,20,30],
              [40,50,60],
              [70,80,90]])
a

# mean
np.mean(a)

np.mean(a,axis=0)

np.mean(a,axis=1)

# std
np.std(a)

np.std(a,axis=0)

np.std(a,axis=1)

# max
np.max(a)

np.max(a,axis=0)

np.max(a,axis=1)

# min
np.min(a)

np.min(a,axis=0)

np.min(a,axis=1)